config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :workouts, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many_attached :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @workouts = Workout.all.order(created_at: :desc).first(6)
    # @workout = Workout.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end


  def show
    @workout = Workout.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
  <section class="jumbotron text-center" style="background-image: url('<%= cloudinary_url("https://res.cloudinary.com/dku8zy35b/image/upload/v1592578733/e4xidmvfmj8k3a52g8n8vohkl9nm.jpg", gravity: :center, :resource_type => :raw) %>');object-fit:cover;">
    <!--<div class="container">-->
      <div class="content">
        <h1>Together Working Stronger</h1>
        <p class="lead text">Achieve your optimal work-life balance</p>
        <br>
        <p>
          <!-- <form novalidate="novalidate" class="simple_form search" action="/flats?city=Marbella" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
            <div class="search-form-control form-group">
              <%#= form_tag flats_path, method: :get do %>
                <%#= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Enter your city"
                %>
              <%# end %>
            </div>
          </form> -->
        </p>
      </div>
  </section>
<div class="container">
    <h2 class="title-new-listings">Top rated Workouts</h2>
    <div class="grid-container">
      <%@workouts.each do |workout|%>
        <%= link_to workout_path(workout), class: "card-link" do %>
          <div class="card-trip">
            <%# if workout.photos.attached? %>
              <%#= cl_image_tag workout.photos %>
            <%# else %>
              <%= image_tag "https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80", opacity: 0.9, crop: :thumb, width: 150, height: 150 %>
            <%# end %>
            <div class="card-content">
              <div class="card-trip-infos">
                <div>
                  <h2><%= workout.title %></h2>
                  <div class="city-info">
                    <i class="fas fa-dumbbell"></i><p><%=workout.sport%></p>
                  </div>
                </div>
              <h2 class="card-trip-pricing"><%= workout.duration %> min</h2>
              </div>
            </div>
          </div>
        <% end %>
      <%end%>
    </div>
  </div>
</main>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-transparent">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dku8zy35b/image/upload/v1592862777/Strong_logo_hmitpn.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_white.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-lewagon-white">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://imagizer.imageshack.com/img922/2089/6PYv26.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
            <%= link_to "Add an offer", new_flat_path, class: "nav-link" %>
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>


          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.xing.com/image/9_7_a_30d0e98c7_26642083_1/niklas-brackmann-foto.1024x1024.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Add an offer", new_flat_path, class: "nav-link" %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/workouts/index.html.erb
<h1>Workout</h1>

<div class="container">
  <h1 class="title-offers">All the available workouts</h1>
  <div class="grid-container">
    <%@workouts.each do |workout|%>
    <div class="card-trip">
      <%# if workout.photo.attached? %>
      <%#= cl_image_tag workout.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face %>
      <%# else %>
      <%= image_tag "https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80", opacity: 0.9, crop: :thumb, width: 150, height: 150 %>
      <%# end %>
      <div class="card-content">
        <div class="card-trip-infos">
          <div>
            <h2><%= workout.title %></h2>
          </div>
          <h2 class="card-trip-pricing"><%= workout.duration %> min</h2>
          <h2><%= workout.sport %></h2>
        </div>
        <div class="button-offer-container">
          <%=link_to "Check Workout", workout_path(workout), class: "btn button-offer" %>
        </div>
      </div>
    </div>

  <%end%>
  </div>
</div>

app/views/workouts/show.html.erb
<!-- <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item">
      <img src="https://www.pexels.com/photo/photo-of-woman-doing-yoga-2294353" class="d-block w-100" >
    </div>
    <div class="carousel-item">
      <img src="https://www.pexels.com/photo/man-working-out-2294361" class="d-block w-100" >
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
 -->
<div class="card-show-infos">
  <div>
    <%= cl_image_tag("https://res.cloudinary.com/dku8zy35b/image/upload/v1592519212/arms-abs-workout-betina-gozo-1570037480_vcwxjh.jpg",
      width: 400, height: 300, crop: :fill)  %>
    <%# @article.photos.each do |photo| %>
    <%#= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <%# end %>
    <h2 id="title"><%= @workout.title %></h2>
    <br>
    <p><%= @workout.sport %></p>
    <br>
    <p><%= @workout.intensity %></p>
  </div>
  <!-- <h2 class="card-show-user"><%#= @flat.user.email %></h2> -->
  <h2 class="card-show-pricing"><%= @workout.duration %> min </h2>
</div>